@layout('layouts.website')

@section('page')
<div class="biz">

<h3>Privacy Policy:</h3>

<h4>Website Visitors</h4>
<p>Like most website operators, {{ Config::get('pv.company') }} collects non-personally-identifying information of the sort that web browsers and servers typically make available, such as the browser type, language preference, referring site, and the date and time of each visitor request. {{ Config::get('pv.company') }}’s purpose in collecting non-personally identifying information is to better understand how {{ Config::get('pv.company') }}’s visitors use its website. From time to time, {{ Config::get('pv.company') }} may release non-personally-identifying information in the aggregate, e.g., by publishing a report on trends in the usage of its website.</p>
<p>{{ Config::get('pv.company') }} also collects potentially personally-identifying information like Internet Protocol (IP) addresses. {{ Config::get('pv.company') }} only discloses IP addresses under the same circumstances that it uses and discloses personally-identifying information as described below.</p>
<h4>Gathering of Personally-Identifying Information</h4>
<p>Certain visitors to {{ Config::get('pv.company') }}’s websites choose to interact with {{ Config::get('pv.company') }} in ways that require {{ Config::get('pv.company') }} to gather personally-identifying information. The amount and type of information that {{ Config::get('pv.company') }} gathers depends on the nature of the interaction. {{ Config::get('pv.company') }} does not disclose personally-identifying information other than as described below. And visitors can always refuse to supply personally-identifying information, with the caveat that it may prevent them from engaging in certain website-related activities.</p>
<h4>Aggregated Statistics</h4>
<p>{{ Config::get('pv.company') }} may collect statistics about the behavior of visitors to its websites. However, {{ Config::get('pv.company') }} does not disclose personally-identifying information other than as described below.</p>
<h4>Protection of Certain Personally-Identifying Information</h4>
<p>{{ Config::get('pv.company') }} discloses potentially personally-identifying and personally-identifying information only to those of its employees, contractors and affiliated organizations that (i) need to know that information in order to process it on {{ Config::get('pv.company') }}’s behalf or to provide services available at {{ Config::get('pv.company') }}’s websites, and (ii) that have agreed not to disclose it to others. Some of those employees, contractors and affiliated organizations may be located outside of your home country; by using {{ Config::get('pv.company') }}’s websites, you consent to the transfer of such information to them. {{ Config::get('pv.company') }} will not rent or sell potentially personally-identifying and personally-identifying information to anyone. Other than to its employees, contractors and affiliated organizations, as described above, {{ Config::get('pv.company') }} discloses potentially personally-identifying and personally-identifying information only in response to a subpoena, court order or other governmental request, or when {{ Config::get('pv.company') }} believes in good faith that disclosure is reasonably necessary to protect the property or rights of {{ Config::get('pv.company') }}, third parties or the public at large.</p>
<h4>Cookies</h4>
<p>A cookie is a string of information that a website stores on a visitor’s computer, and that the visitor’s browser provides to the website each time the visitor returns. {{ Config::get('pv.company') }} uses cookies to help {{ Config::get('pv.company') }} identify and track visitors, their usage of {{ Config::get('pv.company') }} website, and their website access preferences. {{ Config::get('pv.company') }} visitors who do not wish to have cookies placed on their computers should set their browsers to refuse cookies before using {{ Config::get('pv.company') }}’s websites, with the drawback that certain features of {{ Config::get('pv.company') }}’s websites may not function properly without the aid of cookies.</p>
<h4>Business Transfers</h4>
<p>If {{ Config::get('pv.company') }}, or substantially all of its assets, were acquired, or in the unlikely event that {{ Config::get('pv.company') }} goes out of business or enters bankruptcy, user information would be one of the assets that is transferred or acquired by a third party. You acknowledge that such transfers may occur, and that any acquirer of {{ Config::get('pv.company') }} may continue to use your personal information as set forth in this policy.</p>
<h4>Ads</h4>
<p>Ads appearing on any of our websites may be delivered to users by advertising partners, who may set cookies. These cookies allow the ad server to recognize your computer each time they send you an online advertisement to compile information about you or others who use your computer. This information allows ad networks to, among other things, deliver targeted advertisements that they believe will be of most interest to you. This Privacy Policy covers the use of cookies by {{ Config::get('pv.company') }} and does not cover the use of cookies by any advertisers.</p>
<h4>Privacy Policy Changes</h4>
<p>Although most changes are likely to be minor, {{ Config::get('pv.company') }} may change its Privacy Policy from time to time, and in {{ Config::get('pv.company') }}’s sole discretion. {{ Config::get('pv.company') }} encourages visitors to frequently check this page for any changes to its Privacy Policy.</p>

</div>
@endsection