@layout('layouts.website')

@section('page')
<div class="biz">

<h3>Terms of Service:</h3>
<p>The following terms and conditions govern all use of the {{ URL::base() }} website and all content, services and products available at or through the website. The Website is owned and operated by {{ Config::get('pv.company') }}. The Website is offered subject to your acceptance without modification of all of the terms and conditions contained herein and all other operating rules, policies (including, without limitation, <a href="{{ URL::to('privacy') }}">our Privacy Policy</a>) and procedures that may be published from time to time on this Site by {{ Config::get('pv.company') }} (collectively, the “Agreement”).</p>
<p>Please read this Agreement carefully before accessing or using the Website. By accessing or using any part of the web site, you agree to become bound by the terms and conditions of this agreement. If you do not agree to all the terms and conditions of this agreement, then you may not access the Website or use any services. If these terms and conditions are considered an offer by {{ Config::get('pv.company') }}, acceptance is expressly limited to these terms. The Website is available only to individuals who are at least 13 years old.</p>
<ol>
<li><strong>Your {{ URL::base() }} Access.</strong> If you save a text note via the service, you are responsible for maintaining the security of the note and password. {{ Config::get('pv.company') }} has no knowledge of the content of notes. {{ Config::get('pv.company') }} will not be liable for any acts or omissions by You, including any damages of any kind incurred as a result of such acts or omissions.</li>
<li>the Text Note does not contain or install any viruses, worms, malware, Trojan horses or other harmful or destructive content;</li>
<li>the Text Note is not spam, is not machine- or randomly-generated, and does not contain unethical or unwanted commercial content designed to drive traffic to third party sites or boost the search engine rankings of third party sites, or to further unlawful acts (such as phishing) or mislead recipients as to the source of the material (such as spoofing);</li>
</ul>
<li>Without limiting any of those representations or warranties, {{ Config::get('pv.company') }} has the right (though not the obligation) to, in {{ Config::get('pv.company') }}'s sole discretion (i) refuse or remove any content that, in {{ Config::get('pv.company') }} reasonable opinion, violates any {{ Config::get('pv.company') }} policy or is in any way harmful or objectionable, or (ii) terminate or deny access to and use of the Website to any individual or entity for any reason, in {{ Config::get('pv.company') }}'s' sole discretion. {{ Config::get('pv.company') }} will have no obligation to provide a refund of any amounts previously paid.
</li>
<li><strong>Responsibility of Website Visitors.</strong> {{ Config::get('pv.company') }} has not reviewed, and cannot review, all of the material, including computer software, posted to the Website, and cannot therefore be responsible for that material’s content, use or effects. By operating the Website, {{ Config::get('pv.company') }} does not represent or imply that it endorses the material there posted, or that it believes such material to be accurate, useful or non-harmful. You are responsible for taking precautions as necessary to protect yourself and your computer systems from viruses, worms, Trojan horses, and other harmful or destructive content. The Website may contain content that is offensive, indecent, or otherwise objectionable, as well as content containing technical inaccuracies, typographical mistakes, and other errors. The Website may also contain material that violates the privacy or publicity rights, or infringes the intellectual property and other proprietary rights, of third parties, or the downloading, copying or use of which is subject to additional terms and conditions, stated or unstated. {{ Config::get('pv.company') }} disclaims any responsibility for any harm resulting from the use by visitors of the Website, or from any downloading by those visitors of content there posted.</li>
<li><strong>Content Posted on Other Websites.</strong> We have not reviewed, and cannot review, all of the material, including computer software, made available through the websites and webpages to which {{ URL::base() }} links, and that link to {{ URL::base() }}. {{ Config::get('pv.company') }} does not have any control over those websites and webpages, and is not responsible for their contents or their use. By linking to a  website or webpage, {{ Config::get('pv.company') }} does not represent or imply that it endorses such website or webpage. You are responsible for taking precautions as necessary to protect yourself and your computer systems from viruses, worms, Trojan horses, and other harmful or destructive content. {{ Config::get('pv.company') }} disclaims any responsibility for any harm resulting from your use of websites and webpages.</li>
<li><strong>Intellectual Property.</strong> This Agreement does not transfer from {{ Config::get('pv.company') }} to you any {{ Config::get('pv.company') }} or third party intellectual property, and all right, title and interest in and to such property will remain (as between the parties) solely with {{ Config::get('pv.company') }}. {{ Config::get('pv.company') }}, {{ URL::base() }}, the {{ URL::base() }} logo, and all other trademarks, service marks, graphics and logos used in connection with {{ URL::base() }}, or the Website are trademarks or registered trademarks of {{ Config::get('pv.company') }} or {{ Config::get('pv.company') }}'s licensors. Other trademarks, service marks, graphics and logos used in connection with the Website may be the trademarks of other third parties. Your use of the Website grants you no right or license to reproduce or otherwise use any {{ Config::get('pv.company') }} or third-party trademarks.</li>
<li><strong>Changes. </strong>{{ Config::get('pv.company') }} reserves the right, at its sole discretion, to modify or replace any part of this Agreement. It is your responsibility to check this Agreement periodically for changes. Your continued use of or access to the Website following the posting of any changes to this Agreement constitutes acceptance of those changes. {{ Config::get('pv.company') }} may also, in the future, offer new services and/or features through the Website (including, the release of new tools and resources). Such new features and/or services shall be subject to the terms and conditions of this Agreement. <strong><br />
</strong></li>
<li><strong>Termination. </strong>{{ Config::get('pv.company') }} may terminate your access to all or any part of the Website at any time, with or without cause, with or without notice, effective immediately. If you wish to terminate this Agreement you may simply discontinue using the Website. All provisions of this Agreement which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity and limitations of liability. <strong><br />
</strong></li>
<li class="important"><strong>Disclaimer of Warranties.</strong> The Website is provided &#8220;as is&#8221;. {{ Config::get('pv.company') }} and its suppliers and licensors hereby disclaim all warranties of any kind, express or implied, including, without limitation, the warranties of merchantability, fitness for a particular purpose and non-infringement. Neither {{ Config::get('pv.company') }} nor its suppliers and licensors, makes any warranty that the Website will be error free or that access thereto will be continuous or uninterrupted. You understand that you download from, or otherwise obtain content or services through, the Website at your own discretion and risk.</li>
<li class="important"><strong>Limitation of Liability.</strong> In no event will {{ Config::get('pv.company') }}, or its suppliers or licensors, be liable with respect to any subject matter of this agreement under any contract, negligence, strict liability or other legal or equitable theory for: (i) any special, incidental or consequential damages; (ii) the cost of procurement for substitute products or services; (iii) for interruption of use or loss or corruption or unintended release of data; or (iv) for any amounts that exceed the fees paid by you to {{ Config::get('pv.company') }} under this agreement during the twelve (12) month period prior to the cause of action. {{ Config::get('pv.company') }} shall have no liability for any failure or delay due to matters beyond their reasonable control. The foregoing shall not apply to the extent prohibited by applicable law.</li>
<li><strong>General Representation and Warranty.</strong> You represent and warrant that (i) your use of the Website will be in strict accordance with the {{ Config::get('pv.company') }} Privacy Policy, with this Agreement and with all applicable laws and regulations (including without limitation any local laws or regulations in your country, state, city, or other governmental area, regarding online conduct and acceptable content, and including all applicable laws regarding the transmission of technical data exported from the United States or the country in which you reside) and (ii) your use of the Website will not infringe or misappropriate the intellectual property rights of any third party.</li>
<li><strong>Indemnification.</strong> You agree to indemnify and hold harmless {{ Config::get('pv.company') }}, its contractors, and its licensors, and their respective directors, officers, employees and agents from and against any and all claims and expenses, including attorneys’ fees, arising out of your use of the Website, including but not limited to your violation of this Agreement.</li>
<li><strong>Miscellaneous.</strong> This Agreement constitutes the entire agreement between {{ Config::get('pv.company') }} and you concerning the subject matter hereof, and they may only be modified by a written amendment signed by an authorized executive of {{ Config::get('pv.company') }}, or by the posting by {{ Config::get('pv.company') }} of a revised version. Except to the extent applicable law, if any, provides otherwise, this Agreement, any access to or use of the Website will be governed by the laws of the state of New York, U.S.A. Except for claims for injunctive or equitable relief or claims regarding intellectual property rights (which may be brought in any competent court without the posting of a bond), any dispute arising under this Agreement shall be finally settled in accordance with the Comprehensive Arbitration Rules of the Judicial Arbitration and Mediation Service, Inc. (“JAMS”) by three arbitrators appointed in accordance with such Rules. The arbitration shall take place in New York, NY, in the English language and the arbitral decision may be enforced in any court. The prevailing party in any action or proceeding to enforce this Agreement shall be entitled to costs and attorneys’ fees. If any part of this Agreement is held invalid or unenforceable, that part will be construed to reflect the parties’ original intent, and the remaining portions will remain in full force and effect. A waiver by either party of any term or condition of this Agreement or any breach thereof, in any one instance, will not waive such term or condition or any subsequent breach thereof. You may assign your rights under this Agreement to any party that consents to, and agrees to be bound by, its terms and conditions; {{ Config::get('pv.company') }} may assign its rights under this Agreement without condition. This Agreement will be binding upon and will inure to the benefit of the parties, their successors and permitted assigns.</li>
</ol>

</div>
@endsection